name: Trivy Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 6 * * 1'  # setiap Senin pukul 06:00

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          TRIVY_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r .tag_name)
          wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_VERSION}/trivy_${TRIVY_VERSION#v}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION#v}_Linux-64bit.deb


      - name: Run Trivy filesystem scan
        run: trivy fs --exit-code 1 --severity CRITICAL,HIGH ./ --format sarif --output trivy-results.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Upload Trivy artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.sarif
